### ISSUE TITLE
Splash screen image for Apple required

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-app-stockpile#1]
We should add the following tag to index.html:

```
<link  rel="apple-touch-startup-image"  href="img/Default-Portrait.png">
```

and create an image to go with it. This will be used when the app is started from the home screen of an 🍎  device

**Comment by devgeeks** [comment]
Yeah, all of the image assets need doing. When saved to home screen at the moment it has the Vue logo as the icon, etc.

**Comment by devgeeks** [comment]
Now that there is an icon, I just need the correct sizes in the correct places.
