### ISSUE TITLE
Search Result does't scroll when user tries to scroll before results load

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-stockpile#7]
Platform:

- PhoneGap Developer App on iPhone 6

Steps to reproduce:

1. search for something new (so you don't have the result cached)
2. on search results screen, start trying to scroll before any results are displayed
3. search results will appear, but the results will not scroll

**Comment by devgeeks** [comment]
Ugh. So this is with the latest version? Does it scroll fine once the results load if you leave it alone till they do? Is it only if you try scrolling early?

**Comment by hermwong** [comment]
here are a few of the various test cases that I used.

**Test Case 1:**

When I try to scroll early (on a new search topic - e.g. used "dog"), the results won't scroll at all after they've loaded.

Quit the app and then searching using "dog" again and tried to scroll early - this scenario allowed me to scroll the search results after they loaded and also allowed the infinite loading of additional results.

**Test Case 2:**

Try a new topic to search (e.g. used "cat"), tried to scroll early before results loaded, the results won't scroll at all after they've loaded.

Go back to search screen and use a new search topic (e.g. used "frog"),  tried to scroll early before results loaded, the results won't scroll at all after they've loaded.

**Test Case 3:**

Try a new topic to search (e.g. used "cow"), tried to scroll early before results loaded, the results won't scroll at all after they've loaded.

Quit the app and then searching using a new search topic (e.g. used "horse"), tried to scroll early before results loaded, the results won't scroll at all after they've loaded.

**Comment by hermwong** [comment]
The test was done from a local build off a clone of master on this morning (Aug. 23rd at around 10:30am-ish PST).

EDIT: updated to correct date.
